import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import type { McpAuthContext } from "@/lib/mcp/auth";
import { assistantTools } from "./tools";
import { buildSystemPrompt } from "./prompts";
import type { AssistantEvent } from "./protocol";
import type { AssistantMessage } from "@/types";

const MODEL = "claude-opus-5";
const MAX_TOKENS = 8192;

const client = new Anthropic();

/**
 * Run one assistant turn, yielding protocol events as they happen.
 *
 * Yields `tool` events because a tool loop plus thinking means several seconds
 * before the first token; without them the user watches a blank pane.
 *
 * The returned generator also accumulates the assistant's text, which the
 * caller persists — see the `text` events it emits.
 */
export async function* runAssistantTurn(args: {
  ctx: McpAuthContext;
  history: AssistantMessage[];
  activePortfolioName: string | null;
  signal?: AbortSignal;
}): AsyncGenerator<AssistantEvent> {
  const runner = client.beta.messages.toolRunner(
    {
      model: MODEL,
      max_tokens: MAX_TOKENS,
      stream: true,
      // Adaptive thinking is on by default on Opus 5, so there is no `thinking`
      // param here — `budget_tokens` is rejected outright on this model. High
      // effort is what buys multi-step tool reasoning ("compare these two
      // portfolios" is several dependent calls, not one).
      output_config: { effort: "high" },
      system: [
        {
          type: "text",
          text: buildSystemPrompt({
            activePortfolioName: args.activePortfolioName,
          }),
          // Tools serialize before `system`, which serializes before the
          // messages, so one breakpoint here caches the whole stable prefix:
          // every tool definition plus this prompt. That prefix grew several
          // times over when the tool surface expanded, which makes the
          // breakpoint matter more, not less — it is comfortably past the
          // model's 512-token minimum and is re-read on every turn.
          cache_control: { type: "ephemeral" },
        },
      ],
      tools: [
        ...assistantTools(args.ctx),
        // Hosted, so it has no `run` — Anthropic executes it and returns the
        // results inline.
        //
        // Deliberately the BASIC variant, not `web_search_20260209`. The newer
        // one runs code execution internally for dynamic filtering, and the
        // moment that produces a pending tool use the next request in the loop
        // must carry a `container_id`:
        //
        //   400 invalid_request_error — "container_id is required when there
        //   are pending tool uses generated by code execution with tools."
        //
        // `toolRunner` resends the conversation without threading a container
        // through, so every search that reached the filtering step killed the
        // turn. Verified against both variants with the same runner setup.
        // Moving to `_20260209` means owning the message loop by hand.
        //
        // No `code_execution` tool is declared anywhere here either — that is
        // why `calculate` is a plain custom tool.
        {
          type: "web_search_20250305",
          name: "web_search",
          max_uses: 6,
        },
      ],
      messages: args.history.map((m) => ({
        role: m.role,
        content: m.content,
      })),
      // Opus 5 can decline via its safety classifiers. Routing the retry
      // server-side means a decline is recovered rather than shown as a dead end.
      //
      // `fallbacks` appears nowhere in @anthropic-ai/sdk 0.95.1's resource
      // types, so it is introduced by spread rather than by asserting the whole
      // params object. Spread properties skip TypeScript's excess-property
      // check, which keeps every field above fully type-checked; a blanket
      // `as Parameters<typeof client.beta.messages.toolRunner>[0]` would have
      // suppressed errors on `tools`, `system` and `messages` as well.
      ...{ fallbacks: "default" },
    },
    {
      // The beta rides the header rather than a body `betas` key.
      // `BetaToolRunnerParams` derives from the **non-beta**
      // `MessageCreateParams` (BetaToolRunner.d.ts:144) so it has no `betas`
      // field — but `BetaToolRunnerRequestOptions` is
      // `Pick<RequestOptions, 'headers' | 'signal'>`, so this is fully typed.
      headers: { "anthropic-beta": "server-side-fallback-2026-07-01" },
      signal: args.signal,
    },
  );

  // Tools named in one model turn have been executed by the time the next turn
  // begins — that is when we can honestly report them done.
  let pending: string[] = [];
  // A turn that calls a tool says something, calls the tool, then resumes in a
  // NEW message. Concatenating those raw runs the sentences together
  // ("…convert it.Your VOO holding…"), which the renderer then sees as one
  // paragraph — so a break goes in at each message boundary.
  //
  // Per message, not per content block: web search returns cited answers split
  // across several text blocks mid-sentence, and breaking on those shattered
  // every search result into fragments with stray "." lines of their own.
  let emittedText = false;
  let needsBreak = false;

  for await (const messageStream of runner) {
    if (emittedText) needsBreak = true;

    for (const name of pending) {
      yield { kind: "tool", name, status: "done" };
    }
    pending = [];

    for await (const event of messageStream) {
      if (
        event.type === "content_block_delta" &&
        event.delta.type === "text_delta"
      ) {
        if (needsBreak) {
          yield { kind: "text", delta: "\n\n" };
          needsBreak = false;
        }
        emittedText = true;
        yield { kind: "text", delta: event.delta.text };
      }
      // `server_tool_use` is how the hosted web search announces itself —
      // Anthropic runs it, so it never appears as a plain `tool_use` block and
      // would otherwise leave the pane silent for the length of a search.
      if (
        event.type === "content_block_start" &&
        (event.content_block.type === "tool_use" ||
          event.content_block.type === "server_tool_use")
      ) {
        pending.push(event.content_block.name);
        yield { kind: "tool", name: event.content_block.name, status: "running" };
      }
    }

    const message = await messageStream.finalMessage();
    // Check before trusting content: a refused message can be empty.
    if (message.stop_reason === "refusal") {
      yield {
        kind: "error",
        message:
          "I can't help with that one. Try rephrasing, or ask about a different part of the portfolio.",
      };
      return;
    }
  }

  for (const name of pending) {
    yield { kind: "tool", name, status: "done" };
  }
}

const FOLLOWUP_COUNT = 3;

const FOLLOWUP_SCHEMA = {
  type: "object",
  additionalProperties: false,
  required: ["questions"],
  properties: {
    questions: {
      type: "array",
      // `minItems` above 1 is rejected by the API ("for 'array' type, 'minItems'
      // values other than 0 or 1 are not supported"), so the count is asked for
      // in the prompt and enforced by the slice below rather than by schema.
      minItems: 1,
      items: { type: "string", maxLength: 70 },
    },
  },
} as const;

/**
 * The app is analysis-only, and a suggestion chip is the app speaking rather
 * than the model answering — so a "should I sell?" chip would be Port Pulse
 * itself soliciting a trade decision. The prompt asks for none; this is the
 * backstop for when it produces one anyway.
 */
const SOLICITS_TRADE =
  /\b(should|shall|do)\s+i\s+(buy|sell|trim|add|exit|dump|rebalance|hold)\b|\bworth\s+(buying|selling)\b|\btime\s+to\s+(buy|sell)\b|\bwhat\s+should\s+i\s+(buy|sell)\b/i;

/**
 * Three questions the user might reasonably ask next, given the exchange that
 * just happened.
 *
 * A separate short call rather than something parsed out of the main answer:
 * asking the streaming turn to append machine-readable trailer would put markup
 * in front of the user every time the parse drifted, and the answer is already
 * committed to the transcript by the time this runs. Low effort and a small
 * token cap keep it cheap; a failure returns nothing and the UI simply shows no
 * chips, which is why every error path here is swallowed.
 */
export async function generateFollowUps(args: {
  question: string;
  answer: string;
  signal?: AbortSignal;
}): Promise<string[]> {
  try {
    const response = await client.messages.create(
      {
        model: MODEL,
        max_tokens: 512,
        output_config: {
          effort: "low",
          format: { type: "json_schema", schema: FOLLOWUP_SCHEMA },
        },
        system:
          "You suggest what a portfolio owner might ask next. Given a question " +
          "and the answer they just received, write " +
          `${FOLLOWUP_COUNT} short follow-up questions in their voice, each ` +
          "answerable from their own portfolio data. Go somewhere new — do not " +
          "restate what was just answered. No trade advice: never ask whether " +
          "to buy or sell. Under 70 characters each.",
        messages: [
          {
            role: "user",
            content: `They asked: ${args.question}\n\nThey were told: ${args.answer}`,
          },
        ],
      },
      { signal: args.signal },
    );

    const block = response.content.find((b) => b.type === "text");
    if (!block || block.type !== "text") return [];
    const parsed = JSON.parse(block.text) as { questions?: unknown };
    if (!Array.isArray(parsed.questions)) return [];
    return parsed.questions
      .filter((q): q is string => typeof q === "string" && q.trim().length > 0)
      .map((q) => q.trim())
      .filter((q) => !SOLICITS_TRADE.test(q))
      .slice(0, FOLLOWUP_COUNT);
  } catch {
    return [];
  }
}
