// Static sector map for popular US tickers + major ETFs.
// Source: GICS classifications. ETFs are mapped by their dominant exposure.
// Extend as needed; tickers not present here are returned as null.

export const STATIC_SECTOR_MAP: Record<string, string> = {
  // --- Technology ---
  AAPL: "Technology",
  MSFT: "Technology",
  NVDA: "Technology",
  AVGO: "Technology",
  ORCL: "Technology",
  CRM: "Technology",
  ADBE: "Technology",
  AMD: "Technology",
  INTC: "Technology",
  CSCO: "Technology",
  ACN: "Technology",
  NOW: "Technology",
  IBM: "Technology",
  QCOM: "Technology",
  TXN: "Technology",
  PLTR: "Technology",
  CRWD: "Technology",
  PANW: "Technology",
  SNOW: "Technology",
  DDOG: "Technology",
  NET: "Technology",
  MDB: "Technology",
  ZS: "Technology",
  WDAY: "Technology",
  ANET: "Technology",
  MRVL: "Technology",
  MU: "Technology",
  AMAT: "Technology",
  LRCX: "Technology",
  KLAC: "Technology",
  ASML: "Technology",
  TSM: "Technology",
  ARM: "Technology",
  SHOP: "Technology",
  UBER: "Technology",
  ABNB: "Technology",
  SQ: "Technology",
  COIN: "Technology",
  HOOD: "Technology",

  // --- Communication Services ---
  GOOGL: "Communication Services",
  GOOG: "Communication Services",
  META: "Communication Services",
  NFLX: "Communication Services",
  DIS: "Communication Services",
  CMCSA: "Communication Services",
  TMUS: "Communication Services",
  VZ: "Communication Services",
  T: "Communication Services",
  DUOL: "Communication Services",
  SPOT: "Communication Services",
  RBLX: "Communication Services",
  EA: "Communication Services",
  TTWO: "Communication Services",
  CHTR: "Communication Services",
  WBD: "Communication Services",
  PINS: "Communication Services",
  SNAP: "Communication Services",
  RDDT: "Communication Services",

  // --- Consumer Cyclical ---
  AMZN: "Consumer Cyclical",
  TSLA: "Consumer Cyclical",
  HD: "Consumer Cyclical",
  MCD: "Consumer Cyclical",
  NKE: "Consumer Cyclical",
  LOW: "Consumer Cyclical",
  BKNG: "Consumer Cyclical",
  SBUX: "Consumer Cyclical",
  TJX: "Consumer Cyclical",
  CMG: "Consumer Cyclical",
  ORLY: "Consumer Cyclical",
  AZO: "Consumer Cyclical",
  F: "Consumer Cyclical",
  GM: "Consumer Cyclical",
  RIVN: "Consumer Cyclical",
  LCID: "Consumer Cyclical",
  MAR: "Consumer Cyclical",
  HLT: "Consumer Cyclical",
  YUM: "Consumer Cyclical",
  ROST: "Consumer Cyclical",
  DRI: "Consumer Cyclical",
  EBAY: "Consumer Cyclical",
  ETSY: "Consumer Cyclical",

  // --- Consumer Defensive ---
  WMT: "Consumer Defensive",
  COST: "Consumer Defensive",
  PG: "Consumer Defensive",
  KO: "Consumer Defensive",
  PEP: "Consumer Defensive",
  PM: "Consumer Defensive",
  MO: "Consumer Defensive",
  MDLZ: "Consumer Defensive",
  CL: "Consumer Defensive",
  TGT: "Consumer Defensive",
  KMB: "Consumer Defensive",
  GIS: "Consumer Defensive",
  STZ: "Consumer Defensive",
  KR: "Consumer Defensive",
  MNST: "Consumer Defensive",
  KDP: "Consumer Defensive",
  HSY: "Consumer Defensive",
  CHD: "Consumer Defensive",

  // --- Financial Services ---
  "BRK.A": "Financial Services",
  "BRK.B": "Financial Services",
  JPM: "Financial Services",
  V: "Financial Services",
  MA: "Financial Services",
  BAC: "Financial Services",
  WFC: "Financial Services",
  GS: "Financial Services",
  MS: "Financial Services",
  AXP: "Financial Services",
  C: "Financial Services",
  BLK: "Financial Services",
  SCHW: "Financial Services",
  USB: "Financial Services",
  PNC: "Financial Services",
  TFC: "Financial Services",
  COF: "Financial Services",
  PYPL: "Financial Services",
  SPGI: "Financial Services",
  MCO: "Financial Services",
  CB: "Financial Services",
  AIG: "Financial Services",
  PGR: "Financial Services",
  MET: "Financial Services",
  PRU: "Financial Services",
  AFL: "Financial Services",
  ALL: "Financial Services",
  TRV: "Financial Services",
  AON: "Financial Services",
  MMC: "Financial Services",
  ICE: "Financial Services",
  CME: "Financial Services",
  SOFI: "Financial Services",
  AFRM: "Financial Services",
  NU: "Financial Services",

  // --- Healthcare ---
  LLY: "Healthcare",
  UNH: "Healthcare",
  JNJ: "Healthcare",
  ABBV: "Healthcare",
  MRK: "Healthcare",
  TMO: "Healthcare",
  ABT: "Healthcare",
  PFE: "Healthcare",
  DHR: "Healthcare",
  AMGN: "Healthcare",
  BMY: "Healthcare",
  CVS: "Healthcare",
  ELV: "Healthcare",
  CI: "Healthcare",
  HUM: "Healthcare",
  GILD: "Healthcare",
  ISRG: "Healthcare",
  REGN: "Healthcare",
  VRTX: "Healthcare",
  ZTS: "Healthcare",
  MDT: "Healthcare",
  SYK: "Healthcare",
  BSX: "Healthcare",
  EW: "Healthcare",
  BDX: "Healthcare",
  HCA: "Healthcare",
  MRNA: "Healthcare",
  BIIB: "Healthcare",

  // --- Industrials ---
  GE: "Industrials",
  CAT: "Industrials",
  HON: "Industrials",
  RTX: "Industrials",
  LMT: "Industrials",
  BA: "Industrials",
  UNP: "Industrials",
  UPS: "Industrials",
  DE: "Industrials",
  ETN: "Industrials",
  MMM: "Industrials",
  EMR: "Industrials",
  GD: "Industrials",
  CSX: "Industrials",
  NSC: "Industrials",
  FDX: "Industrials",
  ITW: "Industrials",
  WM: "Industrials",
  CARR: "Industrials",
  PCAR: "Industrials",
  PH: "Industrials",
  CMI: "Industrials",
  NOC: "Industrials",
  TDG: "Industrials",
  LHX: "Industrials",
  GEV: "Industrials",
  PWR: "Industrials",

  // --- Energy ---
  XOM: "Energy",
  CVX: "Energy",
  COP: "Energy",
  EOG: "Energy",
  SLB: "Energy",
  MPC: "Energy",
  PSX: "Energy",
  VLO: "Energy",
  OXY: "Energy",
  PXD: "Energy",
  HES: "Energy",
  WMB: "Energy",
  KMI: "Energy",
  OKE: "Energy",
  FANG: "Energy",

  // --- Basic Materials ---
  LIN: "Basic Materials",
  SHW: "Basic Materials",
  APD: "Basic Materials",
  ECL: "Basic Materials",
  FCX: "Basic Materials",
  NEM: "Basic Materials",
  DOW: "Basic Materials",
  DD: "Basic Materials",
  NUE: "Basic Materials",
  CTVA: "Basic Materials",
  PPG: "Basic Materials",

  // --- Utilities ---
  NEE: "Utilities",
  SO: "Utilities",
  DUK: "Utilities",
  SRE: "Utilities",
  AEP: "Utilities",
  D: "Utilities",
  EXC: "Utilities",
  XEL: "Utilities",
  PCG: "Utilities",
  ED: "Utilities",
  WEC: "Utilities",
  ES: "Utilities",
  PEG: "Utilities",
  AWK: "Utilities",
  CEG: "Utilities",
  VST: "Utilities",

  // --- Real Estate ---
  PLD: "Real Estate",
  AMT: "Real Estate",
  EQIX: "Real Estate",
  CCI: "Real Estate",
  PSA: "Real Estate",
  SPG: "Real Estate",
  O: "Real Estate",
  WELL: "Real Estate",
  DLR: "Real Estate",
  VICI: "Real Estate",

  // --- Broad-market ETFs (assigned to the dominant exposure) ---
  SPY: "Diversified",
  VOO: "Diversified",
  IVV: "Diversified",
  VTI: "Diversified",
  QQQ: "Technology",
  VGT: "Technology",
  XLK: "Technology",
  SMH: "Technology",
  SOXX: "Technology",
  ARKK: "Technology",
  XLF: "Financial Services",
  KRE: "Financial Services",
  XLV: "Healthcare",
  IBB: "Healthcare",
  XLY: "Consumer Cyclical",
  XLP: "Consumer Defensive",
  XLE: "Energy",
  XLI: "Industrials",
  XLB: "Basic Materials",
  XLU: "Utilities",
  XLRE: "Real Estate",
  IWM: "Diversified",
  DIA: "Diversified",
  EFA: "Diversified",
  VEA: "Diversified",
  VWO: "Diversified",
  IEMG: "Diversified",
  AGG: "Bonds",
  BND: "Bonds",
  TLT: "Bonds",
  IEF: "Bonds",
  LQD: "Bonds",
  HYG: "Bonds",
  GLD: "Commodities",
  SLV: "Commodities",
  IAU: "Commodities",
  USO: "Commodities",
};

export function lookupSector(symbol: string): string | null {
  return STATIC_SECTOR_MAP[symbol.toUpperCase()] ?? null;
}
